baseURL = "https://whentheycamedown.com"
languageCode = "en-us"
title = "whentheycamedown"
theme = "hugo-nederburg-theme"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "https://github.com/Gorcenski/whentheycamedown/blob/master/README.md"
name = "Contribute"
weight = 1
# [[menu.main]]
# url = "/tags"
# name = "Tags"
# weight = 4
# [[menu.main]]
# url = "/posts"
# name = "Archive"
# weight = 1
# # [[menu.main]]
# # url = "/episodes"
# # name = "Episodes"
# # weight = 2
# [[menu.main]]
# url = "/index.xml"
# name = "RSS Feed"
# weight = 5