on: [push]
name: Publish Site
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: gorcenski/github-action-hugo-deploy-to-firebase@master
      with:
        firebase-token: ${{ secrets.wtcd_firebase_deploy }}
        alias: whentheycamedown
        site-dir: website
